name: 'Turn off the test summary PR comments if a user is in a specified Github Team'
author: 'Eloise Taylor'
description: 'Set comment mode on a PR for the test summary action based on the teams a user is in'
branding:
  icon: 'git-pull-request'
  color: 'purple'

inputs:
  default_comment_mode:
    description: "The comment mode to use when a commit author isn't in any Github Teams for suppressing comments on the PR"
    default: 'failures'
    required: false
    
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: true
    
  github_organisation:
    description: 'Github Organisation the team is part of'
    default: ${{ github.repository_owner }} 
    required: false
    
  github_team_for_switching_off_comments:
    description: 'Github Team users can join to suppress comments on their PR'
    default: 'Suppress PR test summary comments'
    required: true
    
outputs:
  test_summary_comment_mode:
    description: "Comment mode"
    value: ${{ env.TEST_SUMMARY_COMMENT_MODE }}

runs:
  using: "composite"
  steps:
  - name: Set publish test results comment_mode flag to the default value
    shell: bash
    run:  echo "TEST_SUMMARY_COMMENT_MODE=${{ inputs.default_comment_mode}}" >> $GITHUB_ENV
    
  - name: Check if user is a member of the team
    uses: tspascoal/get-user-teams-membership@v3
    id: check_if_user_suppressed_comments
    with:
      username: ${{ github.actor }}
      organization: ${{ inputs.github_organisation }}
      team: ${{ inputs.github_team_for_switching_off_comments }}
      GITHUB_TOKEN: ${{ inputs.github_token }}
      
  - name: Set publish test results comment_mode flag to suppress comments on PR if there are failures
    shell: bash
    if: ${{ steps.check_if_user_suppressed_comments.outputs.isTeamMember == 'true' }}
    run:  echo "TEST_SUMMARY_COMMENT_MODE='off'" >> $GITHUB_ENV
